# Generated by Django 3.1.5 on 2021-01-27 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('etat', models.CharField(choices=[('A', 'A'), ('D', 'D')], max_length=255)),
            ],
            options={
                'db_table': 'examen',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('option1', models.CharField(max_length=255)),
                ('option2', models.CharField(max_length=255)),
                ('option3', models.CharField(max_length=255)),
                ('option4', models.CharField(max_length=255)),
                ('corrans', models.CharField(max_length=255)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examen.examen')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
